name: Build

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.read-matrix.outputs.json }}
    steps:
      - uses: actions/checkout@v4
      - id: read-matrix
        run: |
          ruby ./matrix.rb > matrix.json
          echo "json=$(cat matrix.json)" >>"$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v4
        with:
          name: matrix
          path: matrix.json
          if-no-files-found: error
          retention-days: 1

  build:
    needs:
      - matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.matrix.outputs.json)}}
    runs-on: ${{ matrix.runner }}
    env:
      CC: ${{ matrix.compilers.cc }}
      CXX: ${{ matrix.compilers.cxx }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'rbenv/ruby-build'
          path: ruby-build
      - uses: oras-project/setup-oras@v1
      - name: Log in to ghcr.io
        run: |
          printenv GITHUB_TOKEN | oras login ghcr.io --username gh --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print env
        run: |
          env
      - name: Build Ruby
        run: |
          ./ruby-build/bin/ruby-build "$RUBYVER" ruby
          tar cf "$KEY".tar.zst -C ruby .
          oras push --artifact-type=application/x-tar+zstd ghcr.io/hanazuki/ruby-builder:"$KEY" "$KEY".tar.zst
        env:
          RUBYVER: ${{ matrix.ruby }}
          KEY: ${{ matrix.artifact_tag }}

  commit:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: gitconfig
        run: |
          git config --global user.email automate@hanazuki.dev
          git config --global user.name automate
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: matrix
      - name: Git commit
        run: |
          git add -A
          git commit -m 'Update matrix.json'
          git push origin master
